### PR TITLE
Fix add_apt_repository shebang in containers.

### PR DESCRIPTION
**Pull request by xingao267**

### CODE REVIEW

**Comment by xingao267** [comment]
ummmmm, I just realized that software-properties-common is not installed in our containers, and add-apt-repository is part of that. We cannot edit that file before shipping our containers. Or we could install software-properties-common in our containers.

**Comment by nlopezgi** [comment]
lets install it

**Comment by nlopezgi** [comment]
hmm , software properties common includes lots of things. Can we narrow down what package is needed for this specific issue.

**Comment by xingao267** [comment]
Looks like a bunch of locale files https://packages.debian.org/sid/all/software-properties-common/filelist. The total installed size is not big though, 458.0 kB

**Comment by xingao267** [comment]
But it does depend on a lot of things. Let me see.

**Pull request closed without merging**
