### PR TITLE
rbe_autoconfig: add 'pull' attribute

### PR DESCRIPTION
**Pull request by laszlocsomor**
The new 'pull' attribute allows controlling
whether rbe_autoconfig is allowed to pull the
container from a registry. Disabling this can be
helpful while developing a custom container that
is not yet pushed to a registry.

### CODE REVIEW

**Comment by laszlocsomor** [comment]
@googlebot I fixed it.

**Comment by laszlocsomor** [comment]
Thanks! I haven't figured out the CLA story -- both accounts are mine, and the CLA is signed for one of them. Shall I create a new PR?

**Comment by smukherj1** [comment]
> Thanks! I haven't figured out the CLA story -- both accounts are mine, and the CLA is signed for one of them. Shall I create a new PR?

Yeah creating a new PR and using the same account for all commits might be the easiest thing to do.

Also, note that buildkite is failing with the following buildifier issue:
```
buildifier: found 1 lint issue in your WORKSPACE, BUILD and *.bzl files
rules/rbe_repo.bzl:904: function-docstring: Argument "pull" is not documented.
```

**Comment by laszlocsomor** [comment]
Thanks for the quick answer! Ok, I'll do that and fix the Buildifier issue too.

**Pull request closed without merging**
