### PR TITLE
Minor documentation change.

### PR DESCRIPTION
**Pull request by xingao267**
Also used to test PR workflow.

### CODE REVIEW

**Comment by xingao267** [comment]
@philwo @buchgr Presubmit is not triggered. Do you guys have an idea why?

**Comment by philwo** [comment]
Hi Xin,

I'm sorry - it seems like we're missing quite a few presubmit hooks yet for projects in the bazelbuild org! I went through all our repos now and made a list: https://github.com/bazelbuild/continuous-integration/issues/228

I'll go through it with @buchgr tomorrow and make sure that pre/postsubmit is working for all projects and that we have tooling that allows us to automatically verify that the settings are OK.

I'll ping this PR when we're done.

**Comment by xingao267** [comment]
Thanks a lot Philipp!

**Comment by xingao267** [comment]
@erain let's test the CI in another PR, some work has been done for the syncing issue. Let's merge this one and see if the syncing is fixed.

**Comment by philwo** [comment]
Post- and presubmit checks should now be working for this repo! Please let me know if you encounter any issues. :)

**Pull request merged**
